### ISSUE TITLE
Needing Help new at this!!!

### ISSUE THREAD

**Issue by pelaw24** [tdamdouni/Pythonista#10]
import random

import ui
import sound

label = ui.Label(name='Label')
label2 = ui.Label(name='Label2')
label3 = ui.Label(name='Label3')
label4 = ui.Label(name='Label4')

def button_tapped(sender):
    sound.play_effect('ui:switch4')
    '@type sender: ui.Button'

global shows_result
shows_result = False

if shows_result or label.text == 'MB':
			label.text = title
    
if label.text == 'MB':'Megabucks\n\n'+str(self.draw (1, 46, 6))
if label.text == 'MB': label2.text = str(self.draw (1, 23, 1))

class self:
    def __init__(self):
        draw(a)

    def draw(startPosi, endPosi, interateNumber):
        a = random.sample(range(startPosi, endPosi), interateNumber)
        a.sort()
        
        return a
        
def make_button(title):
    button = ui.Button(action=button_tapped,
        title=title)
    return button

button1 = make_button(title='MB')

view = ui.load_view()
view.add_subview(label)
view.add_subview(label2)
view.add_subview(label3)
view.add_subview(label4)
view.add_subview(button1)
ui.load_view('Testing').present('sheet')

Can’t show result on label 1 & 2 any help

**Comment by tdamdouni** [comment]
Please post this in the Pythonista App Forum. Thanks!

**Comment by tdamdouni** [comment]
Auf Pythonista App Forum verwiesen
