### ISSUE TITLE
SimplexNoise.py has a broken reference

### ISSUE THREAD

**Issue by simon-hibbs** [tdamdouni/Pythonista#5]
The script tries to create a subclass of sk.Scene, but the sk.py  module doesn’t contain such a class. sk.py does import * from SKExample.py, but that doesn’t contain it either. It does define SKScene, but that won’t work.

**Comment by tdamdouni** [comment]
Hi, I think if you search the Pythonista App Forum you will get an answer.

**Comment by tdamdouni** [comment]
Auf Pythonista App Forum verwiesen
